### ISSUE TITLE
No match found for     <%= f.input :password_confirmation, required: true %>

### ISSUE THREAD

**Issue by ghost** [thredded/thredded_create_app#14] opened 2018-11-17 13:44 UTC
Throws an error on the devise step:

The command I ran: `thredded_create_app thredded_test`

Error:

```
bundle exec rails g devise:i18n:views -v confirmations passwords registrations sessions unlocks --quiet
thredded_create_app: No match found for     <%= f.input :password_confirmation, required: true %>
 in app/views/devise/registrations/new.html.erb
```

Looking in `app/views/devise/registrations/new.html.erb`, the line it's trying to match has been split into 3 lines:

```
<%= f.input :password_confirmation,
               required: true,
               input_html: { autocomplete: "new-password" } %>
```

Ruby version: `ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-darwin18]`
Rails version: `5.2.1`

**Comment by glebm** [comment] 2018-11-17 13:51
Thanks! Can you please send a PR?

**Comment by gokaykucuk** [comment] 2018-11-19 23:16
I'm on it

**Comment by gokaykucuk** [comment] 2018-11-19 23:50
@spidey1 the changes are merged to master, can you try it again? And if the problem is resolved, please mark this issue resolved.

**Comment by glebm** [comment] 2018-11-19 23:52
The tests are passing, so I guess it's fixed. Thank you. I'll release a new version once I've tested the generator with `--no-simple-form` as well.

**Closed as completed** 2018-11-19 23:57 UTC
Labels: bug, help wanted
